language: php

php:
 - 5.4
 - 5.5
 - 5.6
 - hhvm

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev
 - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pear install PHP_CodeSniffer; phpenv rehash; fi;'

script:
 - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpcs --standard=PSR2 src/ tests/; fi;'
 - phpunit --coverage-text
